benchmark/flake.nix
Fixes `sh: line 1: perl: command not found`
=> Add pkgs.perl flake.nix

.envrc, .gitignore, flake.nix, result
This PR does three minor things:
1. Expands the `.gitignore` to include some additional paths that should probably be ignored (see [commit message](https://github.com/charmoniumQ/PROBE/commit/fa9f6ed1bdd4502cbcdad21f97f7facd2af08d26) for individual explanations).
2. Adds an `.envrc` file that hooks the devShell so that it automatically gets loaded on directory entry.
3. Formats `flake.nix` with the [`alejandra`](https://github.com/kamadorueda/alejandra) formatter, and adds it to the devShell
The last point is very opinionated, but my rationale for picking alejandra over nixpkgs-fmt is that it produces smaller file diffs, and (in my opinion) is easier to read nix code than nixpkgs-fmt.
=> Small Quality of Life improvements

probe_src/libprobe/Makefile
I would love to say I have a perfect understanding of the implications of this change, but I don't. I think it should be fine for any executable that links libc, but I can't say that with 100% certainty.
=> Added flags to build libprobe.so freestanding

probe_src/libprobe/generated/libc_hooks.c, probe_src/libprobe/generator/libc_hooks_source.c, probe_src/libprobe/src/prov_ops.c, probe_src/libprobe/src/util.c
Fixes two bugs which allowed NULL pointers to be dereferenced under certain circumstances.
1. Some filesystem related functions permit passing NULL as a file path, [this assertion](https://github.com/charmoniumQ/PROBE/blob/5042816c8ab7fe94554c270ecee83fe7edafb5c9/probe_src/libprobe/src/prov_ops.c#L22) failed to check if the path was NULL before dereferencing it with the array subscript operator. 
2. While POSIX.1-2008 does specify an error (EINVAL) to be returned when direnv(3) is passed an invalid directory stream, the [current glibc implementation](https://github.com/bminor/glibc/blob/master/sysdeps/unix/sysv/linux/dirfd.c#L27) is not NULL tolerant, so each call to `dirfd()` has been replaced with a call to a new function `try_dirfd()` which returns `-1` if the directory stream is NULL …
=> Fix `SIGSEGV` bugs in libprobe

probe_src/libprobe/generated/libc_hooks.c, probe_src/libprobe/generator/libc_hooks_source.c
According to [wait(2)](https://www.man7.org/linux/man-pages/man2/waitpid.2.html) the `int* wstatus` parameter in both `wait()` and `waitpid()` can be `NULL` (in which case the exit status is simply ignored), currently libprobe will segfault [here](https://github.com/charmoniumQ/PROBE/blob/a603dee0854f3b48bfab5a15d318dee482819c4a/probe_src/libprobe/generator/libc_hooks_source.c#L2040) when trying to dereference that pointer. This PR fixes the bug by substituting our own `int*` if it's not defined by the caller.
=> Fixed SIGSEGV in wait(2)

flake.nix
Prior to this PR, both darwin platforms would fail when running checks, this fixes this by only adding certain packages to the shell if they're available on the given platform; I'm not sure whether this is truly the best approach, and I'm open to feedback if you don't like this approach.
=> Fix `nix flake check --all-systems` on top-level flake

.github/workflows/ci.yml, Justfile, flake.nix, probe_src/arena/parse_arena.py, probe_src/probe_py/struct_parser.py
P.S: I did not push the code formatting done by `just` since there would have been a lot of file changes
=> CI setup with Justfiles

flake.nix, probe_src/frontend/cli/src/main.rs
Before this is merged the error handling semantics need to be improved a little bit, I'm open to suggestions as to the best way to do this, but some things that might help me would be, knowing:
- Is there any formalized spec for error codes emitted by the python CLI?
- Is there a good way to detect what subcommands are available in the python CLI instead of just catching the error if it's invalid?
=> frontend: pass unknown subcommands to python CLI

.github/workflows/ci.yml, Justfile, README.md, benchmark/flake.nix, docs/flake.nix, docs/lit_review/flake.nix, flake.nix, probe_src/frontend/frontend.nix, probe_src/frontend/lib/src/transcribe.rs, probe_src/frontend/python/probe_py/generated/ops.py, probe_src/tests/A.txt, probe_src/tests/B.txt, probe_src/tests/docker_os_matrix.py, probe_src/tests/test_probe.py
- Test Nix build in CI (previously was only testing devshell + just compile)
- Test in Ubuntu build matrix
- Use Cachix
- Have a script that does tests in Docker containers that are not available on GitHub Actions.
- Fix the actual problem with the build.
=> Test installation in CI

probe_src/libprobe/src/global_state.c, probe_src/libprobe/src/lookup_on_path.c, probe_src/libprobe/src/prov_ops.c, probe_src/tests/test_path_stuff.py
`probe record nonexistent_bin` would segfault due to a shoddy `$PATH` parsing. Using stdlib `strtok_r` is much better than parsing it myself.
=> Add failing tests

probe_src/libprobe/src/lookup_on_path.c
#76 introduced a regression that was somehow not caught in our tests.
```
probe record -f cat flake.nix
env: 'cat' command not found
```
This is because `strtok_r` is _destructive_, inserting `\0` in the string, which makes other users of `$PATH` think it is too short.
This patch fixes the issue by copying `$PATH` before calling `strtok_r`.
=> Fix "env: cat command not found"

probe_src/libprobe/arena/include/arena.h
The current code calls `munmap()` without first invoking `msync()` on the same region: as explained in msync(2), this is a synchronization bug:
> msync() flushes changes made to the in-core copy of a file that was mapped into memory using mmap(2) back to the filesystem.  Without use of this call, there is no guarantee that changes  are  written  back before munmap(2) is called.
This PR breaks out arena unmapping into an inline static function that first calls `msync()` with the `MS_SYNC` flag which requests a page sync for the mapped region and blocks until synchronization is complete, then unmaps the pages with `munmap()`.
=> Fixed syncronization bug with file-backed memory.

probe_src/frontend/cli/src/main.rs, probe_src/frontend/cli/src/record.rs, probe_src/tests/test_integration.py
This removes a dependence on coreutils `env`.
=> CLI launches `probe __exec $cmd...`

probe_py/probe_py/analysis.py, probe_py/tests/test_workflow.py
- Added versions to the file node using the mtime to make the dataflow graph readable. Example df graph for ` probe record bash -c "cat flake.nix > test0 ; head test0 > test0"`
=> feat: versions of filenode to make df readable

libprobe/generator/gen_libc_hooks.py, libprobe/generator/libc_hooks_source.c, libprobe/src/lib.c, libprobe/src/util.c
The old code used the GCC builtin `__builtin_apply` to forward variadic arguments to variadic functions. That is some dark GCC magic with no Clang (or Rust or Zig) equivalent. This PR refactors libc hooks to avoid forwarding variadic arguments in two ways: if we can call a non-variadic function, we do (`execl` calls `unwrapped_execv`); if we can enumerate the possible arguments, we do (`fcntl` and `open` use if-statements to call the "correct" `unwrapped_fcntl` and `unwrapped_open`).
=> Don't use vararg forwarding

.github/workflows/ci.yml, Justfile, cli-wrapper/Cargo.lock, cli-wrapper/cli/Cargo.toml, cli-wrapper/headers/Cargo.toml, cli-wrapper/headers/build.rs, cli-wrapper/lib/Cargo.toml, cli-wrapper/macros/Cargo.toml, flake.nix, libprobe/Makefile, libprobe/README.md, libprobe/generator/gen_libc_hooks.py, libprobe/include/libprobe/prov_ops.h, libprobe/src/arena.c, libprobe/src/arena.h, libprobe/src/debug_logging.h, libprobe/src/env.c, libprobe/src/env.h, libprobe/src/global_state.c, libprobe/src/global_state.h, libprobe/src/inode_table.c, libprobe/src/inode_table.h, libprobe/src/lookup_on_path.c, libprobe/src/lookup_on_path.h, libprobe/src/prov_buffer.c, libprobe/src/prov_buffer.h, libprobe/src/prov_utils.c, libprobe/src/prov_utils.h, libprobe/src/util.c, libprobe/src/util.h
- Add `include-what-you-use` for C; execute `just check-lib`. This removes extraneous includes and even suggests missing includes.
- Run `make check` in `nix flake check`. I made an oversight that `doChecks` is `false` by default, so the checks were not being run.
- Deduplicate checks we are running in CI.
- Run more Rust checks in `just check-cli`. These were already running in `nix flake check`, but this PR also runs them in the `Justfile` for rapid development.
=> Improve checks for compiled code

Justfile, flake.nix, tests/test_record.py
- The parameterization is now full ({all three copy file modes} x {debug opt}).
- The parameter values are now named, rather than the default mode2 and command3.
- We only call downstream PROBE commands once, rather than once per mode (6 modes). The downstream commands are slow, so this speeds up the test suite a lot. It doesn't matter how the data got recorded; once it is validated and parsed, all recording modes are essentially the same.
- The Flake is modified to run integration tests which were previously being unintentionally missed. When #118 removed devshell tests run in CI, this bug, now fixed, caused no tests to be run in CI.
=> Improve PROBE integration tests

libprobe/generator/libc_hooks_source.c, libprobe/include/libprobe/prov_ops.h, libprobe/src/env.c, libprobe/src/env.h, libprobe/src/prov_buffer.c, probe_py/probe_py/analysis.py, tests/test_record.py
This PR removes extraneous counts for the number of arguments and environment variables, where it is neither necessary nor helpful. At one point, we thought the Rust parser would have an easier time reading the `char**` if it knew the number of elements, but we figured out how to do that without knowing the number of elements.
The number of elements is still helpful for performance but not necessary when executing `arena_copy_argv`, but those calls are split into two cases:
- In use-cases where we _already have the number of elements on-hand_, we should pass that to `arena_copy_argv`;
- In cases where we _computed the number specifically for `arena_copy_argv`_ were eliminated. Computing it in calling code is no more efficient than computing it in `arena_copy_argv`.
In both cases, we no …
=> Remove argc count

probe_py/probe_py/analysis.py, probe_py/probe_py/cli.py, probe_py/probe_py/file_closure.py, probe_py/probe_py/parser.py, probe_py/probe_py/ptypes.py, probe_py/probe_py/workflows.py, probe_py/tests/test_graph.py, probe_py/tests/test_workflow.py, tests/test_record.py
Rename `ProvLog` and `prov_log` to `ProbeLog` and `probe_log` and other simple renames.
=> Rename Python variables

cli-wrapper/cli/src/main.rs, flake.nix, libprobe/generator/gen_libc_hooks.py, libprobe/generator/libc_hooks_source.c, libprobe/include/libprobe/prov_ops.h, libprobe/src/global_state.c, libprobe/src/global_state.h, libprobe/src/prov_buffer.c, libprobe/src/prov_utils.c, tests/examples/false.c, tests/examples/true.c, tests/test_record.py
This PR tests all of our example cases in `test_record`. We test that all commands can be recorded, and that the most complex ones admit downstream analysis. Downstream analysis is too slow to run on everything. Enabling these extra tests caught several bugs that are fixed in this PR:
1. Unlike other libc functions, which return a sentinel value on error, `readdir` returns `NULL`, which could also indicate the end of the directory. The only way to disambiguate is to test `errno`. Prior to this PR, libprobe's interposition was not `errno`-correct. The interposition code might call a function that sets `errno`. This PR restores `errno` to its saved value.
2. `copy_to_store` would choke on a directory input or a character file (like `/dev/null`). It is now robust to both. This necessitates …
=> Test and fix recording all examples

cli-wrapper/Cargo.lock, cli-wrapper/cli/src/record.rs, cli-wrapper/headers/Cargo.toml, cli-wrapper/headers/src/lib.rs, cli-wrapper/lib/src/transcribe.rs, libprobe/src/prov_buffer.c, probe_py/probe_py/parser.py, probe_py/probe_py/ptypes.py
ProcessTreeContext is available to libprobe at interposition time. This PR propagates that information into the PROBE log as well. Information, such as copy files mode, can be passed through from the invocation of `probe record` to the downstream analyses.
=> Propagate ProcessTreeContext to PROBE log

libprobe/src/debug_logging.h, libprobe/src/prov_buffer.c
Before this PR, we treated all ops the same.
Now we convert an op into a `struct Path` and an `enum Access` (read, write, truncate_write, etc). Then we send that information to a function that decides whether to copy to store.
=> Refactor copy-to-store logic

libprobe/generator/gen_libc_hooks.py, libprobe/generator/libc_hooks_source.c, libprobe/include/libprobe/prov_ops.h, libprobe/src/prov_buffer.c, libprobe/src/prov_utils.c, probe_py/probe_py/analysis.py, probe_py/probe_py/validators.py, probe_py/tests/test_graph.py
When we close a file descriptor, we should record which path got closed. The Path struct notably includes the mod time of the file, which determines the version of the path. Including that will help us check that our analysis tracked file descriptors and versions correctly. In most cases, it is only a check, but in a few cases, it actually gives us information that we wouldn't otherwise know.
=> Include Path in CloseOp

cli-wrapper/headers/src/lib.rs, cli-wrapper/lib/src/ops.rs, libprobe/generator/gen_libc_hooks.py, libprobe/generator/libc_hooks_source.c, libprobe/include/libprobe/prov_ops.h, libprobe/src/arena.c, libprobe/src/global_state.c, libprobe/src/global_state.h, libprobe/src/prov_buffer.c, libprobe/src/pthread_helper.c, libprobe/src/pthread_helper.h, probe_py/probe_py/hb_graph.py, tests/test_record.py
- Create an ID for pthreads. Prior to this PR, libprobe recorded a `pthread_t` associated with the each thread (either `pthread_self()` or the argument to `pthread_join`/ `pthread_create`). The problem is that the POSIX standard specifies that the `pthread_t` struct should be compared with `pthread_equal`; non-identical struct values can represent the same thread. Therefore, this PR assigns a new thread ID whose bits identify the current thread. `prov_log_record` records the value for the current thread. `pthread_join` and `pthread_create` are modified to log the thread ID of the target.
- Use `pthread_getspecific` instead of `__thread`, which is causing problems for Musl. I also generally revamped how the global state is maintained in libprobe.
=> Restructure thread-local data

flake.nix, libprobe/Makefile, libprobe/generator/libc_hooks_source.c, libprobe/sorted_symbol_versions.py, libprobe/src/util.c, libprobe/src/util.h
Currently libprobe depends on symbols (functions or variables) from Glibc (until #133 is merged), such as `printf` and `dlsym`.The code for those functions is not copied into the libprobe binary, it is requested at runtime. Hopefully whoever is running PROBE has Glibc.
The compiler associates each of those symbols with a _minimum version number_, so it requests `printf@GLIBC_2.3.4`, for example. Each version of Glibc has table going from symbol name to minimum version number that is bug-compatible with the current version. Now when the code is run, it knows to request a version of `printf` at 2.3.4 or newer. The problem is that our Glibc in the dev environment is pretty new, but Glibc on the host (e.g., Ubuntu 20.04) may be older.
The long-term solution is to copy the code into libprobe …
=> Fix glibc error

.envrc, .github/workflows/ci.yml, cli-wrapper/cli/src/main.rs, cli-wrapper/flake.lock, cli-wrapper/flake.nix, cli-wrapper/headers/build.rs, cli-wrapper/lib/build.rs, cli-wrapper/macros/src/lib.rs, cli-wrapper/macros/src/pygen.rs, flake.nix, targets.nix
PROBE CLI is built using Rust. Getting Rust from Nix is [non-trivial](https://nixos.wiki/wiki/Rust), and here we opt for [CraneLib](https://crane.dev/), so as to have fine control over the build process. However, that involves a lot of Nix code. This PR hides most of the CraneLib code in its own flake, `cli-wrapper/flake.nix`, which gets imported into the main flake in the project root.
Also, upgraded Clippy, which raised a few new auto-fixes.
Review by checking that `nix develop --command just lint` works, which calls most of the devtools that need to exist in the devshell. Also check `nix shell '.#probe' --command probe record ls`, which builds and runs PROBE (Rust CLI wrapper + C libprobe).
This PR was split off of the branch `nolibc`, as multiple smaller PRs will be easier to review.
=> Separate cli-wrapper to its own flake

probe_py/probe_py/cli.py, probe_py/probe_py/ptypes.py, probe_py/probe_py/util.py
Speed up by avoiding slow `rich.pretty`. Instead, we use stdlib, indented JSON. It's almost as pretty and much faster.
For dozens of ops, the speed difference doesn't matter, but a PROBE log can easily contain tens of thousands, at which point, the difference is quite noticeable. Since debug-text gets called on every `test_downstream_analysis`, it speeds up the testing workflow quite a bit.
=> Speed up debug text
